name = "project-augurbox"
main = "./workers/index.ts"
compatibility_date = "2025-07-12"

# Static assets configuration for Workers
[assets]
directory = "./apps/augurbox-web/out"
binding = "ASSETS"

# AI binding for Cloudflare AI
[ai]
binding = "AI"

# Custom domain routing
[[routes]]
pattern = "project-augurbox.sirsean.me"
custom_domain = true
