import Link from 'next/link';
import Navbar from '@/components/Navbar';

export default function Home() {
  return (
    <div className="min-h-screen bg-surface grain" style={{background: 'linear-gradient(135deg, #0d0f12 0%, #151821 50%, #1a1d26 100%)'}}>
      <Navbar />
      
      <main className="max-w-4xl mx-auto px-4 py-16 text-center relative z-10">
        <div className="mb-12">
          <h1 className="text-5xl md:text-7xl font-bold mb-6 text-accent" style={{textShadow: '0 0 20px rgba(85, 98, 112, 0.3)'}}>
            AUGURBOX
          </h1>
          <p className="text-xl md:text-2xl mb-8 text-foreground">
            Navigate the augury through AI-generated tarot constructs
          </p>
          <p className="text-lg text-text-dim max-w-2xl mx-auto mb-12 font-mono leading-relaxed">
            Each construct in this collection has been synthesized using advanced neural networks, 
            creating hardscrabble interpretations of ancient divination protocols.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8 mb-16">
          <div className="bg-surface-secondary/60 border border-border rounded-none p-8 hover:bg-surface-secondary/80 transition-all duration-500 hover:shadow-lg hover:shadow-accent/10">
            <div className="text-3xl mb-4 text-accent">◉</div>
            <h2 className="text-xl font-bold mb-4 text-foreground tracking-wide">NEURAL SYNTHESIS</h2>
            <p className="text-text-dim text-sm font-mono leading-relaxed">
              Every construct features imagery generated by Flux AI protocols, creating stark interpretations of traditional divination symbology.
            </p>
          </div>
          
          <div className="bg-surface-secondary/60 border border-border rounded-none p-8 hover:bg-surface-secondary/80 transition-all duration-500 hover:shadow-lg hover:shadow-accent/10">
            <div className="text-3xl mb-4 text-accent">⬟</div>
            <h2 className="text-xl font-bold mb-4 text-foreground tracking-wide">COMPLETE ARCHIVE</h2>
            <p className="text-text-dim text-sm font-mono leading-relaxed">
              Access all 78 constructs of the traditional tarot matrix - 22 Major Arcana and 56 Minor Arcana entities, each with detailed operational parameters.
            </p>
          </div>
        </div>

        <div className="space-y-4">
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/reading"
              className="inline-block bg-accent hover:bg-accent-muted border border-border text-foreground font-mono font-bold py-4 px-8 rounded-none text-sm uppercase tracking-wider transition-all duration-300 hover:shadow-md hover:shadow-accent/20"
            >
              ▶ INITIALIZE READING
            </Link>
            <Link
              href="/cards"
              className="inline-block bg-surface-secondary hover:bg-surface-secondary/80 border border-border text-foreground font-mono font-bold py-4 px-8 rounded-none text-sm uppercase tracking-wider transition-all duration-300 hover:shadow-md hover:shadow-accent/20"
            >
              ◉ ACCESS ARCHIVE
            </Link>
          </div>
          <div className="text-text-dim font-mono text-xs text-center">
            <p>INITIALIZE DIVINATION PROTOCOL</p>
          </div>
        </div>
      </main>
      
      <footer className="text-center py-8 text-text-dim border-t border-border font-mono text-xs relative z-10">
        <p>© 2024 AUGURBOX // NEURAL.DIVINATION.SYSTEMS</p>
      </footer>
    </div>
  );
}
